# Generated by Django 3.0.3 on 2021-07-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='link',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='data',
            name='uuid',
            field=models.CharField(max_length=9),
        ),
    ]
